apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: hl-sa-cwf
spec:
  templates:
  - name: hl-sa-test-information
    resource:
      action: create
      failureCondition: status.failed > 1
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: hl-sa-test-information-job
          namespace: argo
        spec:
          backoffLimit: 2
          template:
            spec:
              restartPolicy: Never
              tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
              containers:
              - image: gaudi-hlsa-ready:1.0
                name: gaudi3-1-23-hlsa
                command:
                - python
                - -m 
                - pytest
                - --cfg
                - json/tests/HL325/PT/config_pt.json
                - -m
                - HL325_pt
                - -k
                - TestInformation
                securityContext:
                  privileged: true
                volumeMounts:
                - name: dev
                  mountPath: /dev
                ports:
                - containerPort: 22
              volumes:
              - name: dev
                hostPath:
                  path: /dev
                  type: DirectoryOrCreate


  - name: hl-sa-test-pci-link-spec
    resource:
      action: create
      failureCondition: status.failed > 1
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: hl-sa-test-pci-link-spec-job
          namespace: argo
        spec:
          backoffLimit: 2
          template:
            spec:
              restartPolicy: Never
              tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
              containers:
              - image: gaudi-hlsa-ready:1.0
                name: gaudi3-1-23-hlsa
                command:
                - python
                - -m 
                - pytest
                - --cfg
                - json/tests/HL325/PT/config_pt.json
                - -m
                - HL325_pt
                - -k
                - TestPCILinkSpec
                securityContext:
                  privileged: true
                volumeMounts:
                - name: dev
                  mountPath: /dev
                ports:
                - containerPort: 22
              volumes:
              - name: dev
                hostPath:
                  path: /dev
                  type: DirectoryOrCreate

